name: Java Calculator CI

on: [push]  # Trigger the workflow on pushes to the repository

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository's code

    - name: Set up Java
      uses: actions/setup-java@v2  # This step sets up Java on the runner
      with:
        java-version: '11'  # Replace with your desired Java version (e.g., '8', '11', '16', etc.)
        distribution: 'adopt'  # Specify the Java distribution

    - name: Compile UI class
      run: |
        javac src/simplejavacalculator/UI.java  # Compile the UI class

    - name: Compile SimpleJavaCalculator class
      run: |
        javac src/simplejavacalculator/SimpleJavaCalculator.java  # Compile the SimpleJavaCalculator class

    - name: Run SimpleJavaCalculator
      run: |
        java -cp src simplejavacalculator.SimpleJavaCalculator  # Run the Java program
