name: Java Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Compile Java code
        run: |
          javac -cp src:lib/* -d . src/*.java
          javac -cp src:lib/*:src/simplejavacalculatorTest -d . src/simplejavacalculatorTest/*.java

      - name: Download JUnit Platform Console
        run: |
          wget -O lib/junit-platform-console-standalone.jar https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.3/junit-platform-console-standalone-1.8.3.jar

      - name: Run JUnit tests
        run: |
          java -cp .:src:lib/*:lib/junit-platform-console-standalone.jar org.junit.platform.console.ConsoleLauncher --select-class simplejavacalculatorTest.CalculatorTest
