name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn package

    - name: Run Unit Tests
      run: mvn test

    - name: Check Code Coverage
      run: mvn jacoco:report

    - name: Convert Code Coverage to JSON
      run: |
        mvn jacoco:report -DreportFile=target/site/jacoco/jacoco.json
      env:
        COVERAGE_FILE: target/site/jacoco/jacoco.json

    - name: Upload Code Coverage
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: target/site/jacoco  # Adjust the path to the directory containing the JSON file
